// Central exports for GraphQL queries
export * from "./collections";
export * from "./categories";
export * from "./customer";
export * from "./product";
export * from "./user";
export * from "./groups";
export * from "./locations";
export * from "./stockTransfers";
export * from "./terminals";
export * from "./cashDrawers";
export * from "./fiscalYears";
export * from "./journalEntries";
export * from "./accounts";
export * from "./coupon";
export * from "./discount";
export * from "./inventory";
export * from "./priceList";
export * from "./promotion";
export * from "./sessions";
export * from './order'
